### ISSUE TITLE
UI Style

### ISSUE THREAD

**Issue by nottix** [andrewn/brew-services-menubar#1]
Hello,

first of all I wanted to congratulate you for the idea, genius!

You can add an icon would be monochromatic black or white? At this time the colored icon is in conflict with the system tray.

**Comment by andrewn** [comment]
Thanks, I'm glad you like it!

I don't really like the coloured icon either. If you can suggest an alternative in the [correct sizes](https://github.com/andrewn/brew-services-menubar/tree/master/BrewServicesMenubar/Assets.xcassets/statusIcon.imageset) then I'd be happy to swap it over!

**Comment by nottix** [comment]
Do you like these?

https://storage.googleapis.com/jb-trans/beer_white%403x.png
https://storage.googleapis.com/jb-trans/beer_black%403x.png

**Comment by andrewn** [comment]
New release is [here](https://github.com/andrewn/brew-services-menubar/releases/tag/v2.0.0). Hope you like it.

**Comment by nottix** [comment]
Thank you @andrewn, now it's very nice!
