### ISSUE TITLE
Doesn't work on Mojave

### ISSUE THREAD

**Issue by Toontje** [andrewn/brew-services-menubar#11]
Menu shows up in the menu bar but no services are shown.

**Comment by Toontje** [comment]
Works for Catalina.

**Comment by Toontje** [comment]
Hello?

**Comment by andrewn** [comment]
👋  I can confirm I also have this problem on Mojave 10.14.6.

I'm not sure when I'll have time to look into this but I'd welcome any help figuring it out or fixing it.

**Comment by andrewn** [comment]
@Toontje I'm closing this as Mojave is two releases of macOS ago so I don't have that version to be able to work on a fix.
