### ISSUE TITLE
Application icon is hard to spot in Launchpad

### ISSUE THREAD

**Issue by stefansundin** [andrewn/brew-services-menubar#15]
I think the new background in macOS 10.15 may have made it harder to spot the app in the launchpad.

![launchpad](https://user-images.githubusercontent.com/1991151/93552925-a9bc8800-f926-11ea-99c6-b3095e712706.png)

I wonder if we can update the icon to be more visible. Maybe make the beer foam yellow or something.

The system icon still looks great though, so that doesn't need to be changed.

**Comment by stefansundin** [comment]
This link from the README is not working unfortunately: https://thenounproject.com/search/?q=beer&i=783212

**Comment by andrewn** [comment]
It looks like this on my Launchpad (macOS 10.15.6)

My desktop background's a light-ish grey colour.

<img width="232" alt="Screenshot 2020-09-21 at 09 48 23" src="https://user-images.githubusercontent.com/1762/93743107-b45d7280-fbef-11ea-8a7c-ceac159d2f5f.png">

But either way, let's try and update the icon to something else for Launchpad. I wonder whether we should make the whole black area yellow for the app icon. Or give the icon a background colour. But keep the current monochrome icon for the menu bar.

**Comment by stefansundin** [comment]
I guess with macOS Big Sur all of the icons have been redesigned to have a rounded square-ish shape, and those who can't fit usually put a white background on their icon, like Chrome. https://9to5google.com/2020/11/17/google-chrome-potential-icon-designs-macos-big-sur/

Maybe that's the best option here. I think it might look decent.

**Comment by andrewn** [comment]
@stefansundin I think that'd be great. I'm busy until Christmas but would accept a PR 😄
