### ISSUE TITLE
Any way to hide certain services?

### ISSUE THREAD

**Issue by gregblass** [andrewn/brew-services-menubar#16]
I just wanted to check to see if there was a way to hide services from the menubar. Services are showing up dependences of things, or old versions of things - both of which I never use / turn on and off.

**Comment by andrewn** [comment]
👋 

The app calls `brew services list` and parses the output of that. It'd be great to have some example output from that command with some more info about what you'd like to hide from the output.

**Comment by andrewn** [comment]
I'm going to close this as it's been 2 years. Please open with more detail.
