### ISSUE TITLE
Persist in menu bar

### ISSUE THREAD

**Issue by LeonardoGentile** [andrewn/brew-services-menubar#17]
Hello,
will the icon re-appear in the menu bar after restart or do you need to launch it each time?
Any configuration to opt in/out?

**Comment by andrewn** [comment]
Hi,

You can have your [Mac open apps automatically when you login](https://support.apple.com/en-gb/guide/mac-help/mh15189/mac). Hope that helps!

**Comment by LeonardoGentile** [comment]
Thanks, I'll do that!

**Comment by andrewn** [comment]
Closing as solved.
