### ISSUE TITLE
Install with brew cask

### ISSUE THREAD

**Issue by stefansundin** [andrewn/brew-services-menubar#5]
Hi there.

I added your program to Homebrew cask, so it's super easy to install for all Homebrew users (which should be all of your users 😄). See https://github.com/caskroom/homebrew-cask/pull/45612

Now you can install with:
```
brew cask install brewservicesmenubar
```

You might want to add it to the README. That's all I came here to say. Have a nice day!

**Comment by andrewn** [comment]
This is a great addition, thanks so much for doing this!

I've added to the README and noted you as a contributor. 🥇 

Have a lovely day.
