### ISSUE TITLE
Services started by sudo

### ISSUE THREAD

**Issue by s-mokrushin** [andrewn/brew-services-menubar#7]
Please add support to manage services started by super user.
Currently this services are disabled. I think a good idea ask user to enter sudo password.

![screenshot 2018-05-22 19 44 51](https://user-images.githubusercontent.com/631518/40377137-d5860dd8-5df8-11e8-8fd6-0fa223f03d94.png)

**Comment by adamzasah** [comment]
I would also appreciate this.

**Comment by adamzasah** [comment]
I imagine there is way for that. What I read so far, macOS expects password from stdin when you run sudo Process in Swift. More here: https://forums.developer.apple.com/thread/91350

Maybe there is some workaround.
